# Generated by Django 3.0.4 on 2020-03-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default='category 0', max_length=300),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
