# Generated by Django 3.0.4 on 2020-03-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200324_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.IntegerField(default='category 0'),
        ),
    ]
